# Generated by Django 6.0.6 on 2026-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='event_type',
            field=models.CharField(choices=[('support', 'Support Agent'), ('tool_call', 'Tool Call'), ('too_result', 'Tool Result'), ('manager', 'Manager Agent'), ('risk', 'Risk Agent'), ('final', 'Final Reply')], max_length=20),
        ),
    ]
