# Generated by Django 6.0.6 on 2026-09-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_agentlog_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentlog',
            old_name='converation',
            new_name='conversation',
        ),
    ]
